on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'base.Dockerfile'

jobs:
  base:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Base
        uses: docker/build-push-action@v2
        with:
          context: .
          file: base.Dockerfile
          push: true
          tags: ghcr.io/hybras/cmsc398i
          platforms: amd64,arm64,arm/v7
          cache-from: type=gha
          cache-to: type=gha,mode=max
